### ISSUE TITLE
readOnly这个按钮 点击了 可以开 再次点击无法关闭（状态）

### ISSUE THREAD

**Issue by fhefh2015** [int64ago/mdnote#1]

**Comment by int64ago** [comment]
是的，这个是特性，因为这个无用户之分
如果你点了 Readonly 之后发给其它用户，而 TA 却可以 disable 掉，就没意义了
我觉得我应该加个提示会不会好点？

**Comment by fhefh2015** [comment]
我第一眼看到 以为可以打开 也可以关闭 嘿嘿

**Comment by int64ago** [comment]
已经优化了这部分的体验，谢谢反馈 :-)
