### ISSUE TITLE
大师兄，发现一个可能不是bug的bug

### ISSUE THREAD

**Issue by pencilCool** [int64ago/mdnote#2]
##abc   这样不会显示成markown 的标题

**Comment by pencilCool** [comment]
看来 这不是bug， github 上也是这样子的~~~

**Comment by int64ago** [comment]
是的，我是用的 [GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) 格式

具体可以看[这里](https://github.com/int64ago/mdnote/blob/master/static/js/md.js#L4)设置

**Comment by pencilCool** [comment]
回复的好快
